# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104JCrE68jfCspkACdySawvAv8ZDtEGXt
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

!kaggle datasets download -d sahilislam007/college-student-placement-factors-dataset

import zipfile
zip_file_path = "/content/college-student-placement-factors-dataset.zip"
extraction_directory = "/content/dataset"
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_directory)

import pandas as pd
import numpy as np

df=pd.read_csv('/content/college-student-placement-factors-dataset.zip')

df.head()



import matplotlib.pyplot as plt

# Map 'Placement' column to numerical values for coloring
df['Placement_numeric'] = df['Placement'].map({'No': 0, 'Yes': 1})

plt.scatter(df['CGPA'],df['IQ'],c=df['Placement_numeric'])

x=df.iloc[:,[1,2,3]]
y=df.iloc[:,[10]]

df['Placement'] = df['Placement'].map({'No': 0, 'Yes': 1})
y.shape

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1)

from sklearn.preprocessing import StandardScaler

scler=StandardScaler()

xtrain=scler.fit_transform(xtrain)
xtest=scler.fit_transform(xtest)

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

clf.fit(xtrain,ytrain)

pred=clf.predict(xtest)

ytest

from sklearn.metrics import accuracy_score

accuracy_score(ytest,pred)